# Generated by Django 2.0.6 on 2018-06-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=60)),
                ('genres', models.CharField(max_length=100)),
                ('imdb_score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('popularity', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
            options={
                'db_table': 'catalogues_movies',
            },
        ),
    ]
